[workspace]

members = [
    "bottomless",
    "bottomless-cli",
    # "libsql-client",
    "sqlc",
    "sqld",
    "sqld-libsql-bindings",
]

[patch.crates-io]
uuid = { git = "https://github.com/psarna/uuid", branch = "stable_v7" }
